name: agevents
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mask_text_input_formatter: ^2.4.0
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  calendar_appbar: ^0.0.6
  google_fonts: ^3.0.1
  provider: ^6.0.3
  fl_chart: ^0.55.0
  flutter_sms: ^2.3.3
  flutter_bloc: ^8.0.1
  graphql_flutter: ^5.1.0
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/animations/